---

#https://docs.fortinet.com/document/fortigate/7.4.0/administration-guide/399023/rest-api-administrator
#https://docs.fortinet.com/document/fortigate/6.2.15/cookbook/294491/administrator-profiles
- name: Enable REST API (CLI)
  ansible.builtin.expect:
    command: "ssh -o StrictHostKeyChecking=no admin@{{ groups['fortianalyzer'][0] }}"
    responses:
      'Password:': "{{ new_password }}" 
      '# ': "{{ api_config }}"
  register: output
  delegate_to: localhost

- name: Enable FortiAnalyzer discovery port (fgfm)
  fortinet.fortianalyzer.faz_cli_system_interface:
    cli_system_interface:
      name: port1
      allowaccess:
      - ping
      - ssh
      - https
      - http
      - fgfm
    state: present