
- name: Get FortiManager devices
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: dvmdb_device
        params:
            adom: "root"
            device: ""
  register: _devices

- name: Debug Devices 
  debug:
    var: _devices.meta.response_data

- debug:
    msg: "Device Name: {{ item.name }}, OS Version: {{ item.os_ver }}, Mgm_Int: {{ item.mgmt_if }}, Mgm IP: {{ item.ip }}"
  loop: "{{ _devices.meta.response_data }}"

- name: Get FortiManager facts system_interface
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: system_interface
        params:
            interface: ""
            device: "{{ item.name }}"
  loop: "{{ _devices.meta.response_data }}"

