
- name: Get FortiManager devices
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: dvmdb_device
        params:
            adom: "root"
            device: ""
  register: _devices

- name: Debug Devices full var 
  ansible.builtin.debug:
    var: _devices.meta.response_data

- name: Debug Devices main info
  ansible.builtin.debug:
    msg: "Device Name: {{ item.name }}, OS Version: {{ item.os_ver }}, Mgm_Int: {{ item.mgmt_if }}, Mgm IP: {{ item.ip }}"
  loop: "{{ _devices.meta.response_data }}"

- name: Discovering devices from FortiManager 
  fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
    bypass_validation: true
    enable_log: true
    dvm_cmd_discover_device:
      device:
        adm_pass: "{{ fortinet_admin_password }}"
        adm_usr: "{{ fortinet_admin_user }}"
        ip: "{{ item.ip }}"
  loop: "{{ _devices.meta.response_data }}"
  register: _probed_devices

- name: Debug Probed Devices full var 
  ansible.builtin.debug:
    var: _probed_devices.meta.response_data
