---

# - name: Enable FortiGate discovery port (fgfm)
#   fortinet.fortios.fortios_system_interface:
#     vdom: "{{ domain }}"
#     access_token: "{{ fortigate_token }}"
#     state: present
#     system_interface:
#       name: port1
#       interface: port1
#       allowaccess:
#       - ping
#       - https
#       - ssh
#       - http
#       - fgfm

- name: Configure IPv4 addresses
  fortinet.fortios.fortios_system_interface:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    state: present
    system_interface:
      "{{ item }}"
  loop: "{{ ipv4_address }}"

- name: Configure IPv4 static routing
  fortinet.fortios.fortios_router_static:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    state: present
    router_static:
      "{{ item }}"
  loop: "{{ ipv4_routing }}"
  ignore_errors: true

