---

- name: AWS Fortinet deployment role
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  tasks:
    - include_role: 
        name: aws_deploy_fortinet
