---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'
  - include_role:
      name: utils_hosts_aws
    when: infra == 'aws'

- name: Fortinet FortiManager roles
  hosts: fortimanager
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  tasks:
    - name: Discovering FortiGate device from FortiManager 
      fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
        bypass_validation: true
        enable_log: true
        dvm_cmd_discover_device:
          device:
            adm_pass: "admin"
            adm_usr: "adminadmin"
            ip: "10.0.0.104"
      register: _probed_fortigate
      ignore_errors: true

    - name: Add FortiGate device to FortiManager
      fortinet.fortimanager.fmgr_dvm_cmd_add_device:
        dvm_cmd_add_device:
          adom: "root"
          device:
            adm_usr: "admin"
            adm_pass: "admin"
            desc: 'The device was added using Ansible'
            ip: "10.0.0.104"
            mgmt_mode: 'fmg'
            name: "FGTAWSXFPH0A7X9D" 
            sn: "FGTAWSXFPH0A7X9D" 
      ignore_errors: true

    - name: Discovering FortiAnalyzer device from FortiManager 
      fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
        bypass_validation: true
        enable_log: true
        dvm_cmd_discover_device:
          device:
            adm_pass: "admin"
            adm_usr: "adminadmin"
            ip: "10.0.0.220"
      register: _probed_fortianalyzer
      ignore_errors: yes

    - name: Add FortiAnalyzer device to FortiManager
      fortinet.fortimanager.fmgr_dvm_cmd_add_device:
        dvm_cmd_add_device:
          adom: "root"
          device:
            adm_usr: "admin"
            adm_pass: "admin"
            desc: 'The device was added using Ansible'
            ip: "10.0.0.220"
            mgmt_mode: "fmg"
            name: 'FAZVM64-AWS'
            sn: 'FAZ-VMTM23017706'
      ignore_errors: yes

- name: Get FortiManager facts
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: dvmdb_adom
        params:
          adom: "{{ domain }}"
  ignore_errors: yes 

- name: "Get FortiManager facts dvmdb_adom {{ domain }}"
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: dvmdb_adom
        params:
          adom: "{{ domain }}"
  ignore_errors: yes

- name: Get FortiManager facts dvmdb_device
  fortinet.fortimanager.fmgr_fact:
    facts:
        selector: dvmdb_device
        params:
            adom: "{{ domain }}"
            device: ""
  ignore_errors: yes