---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'
  - include_role:
      name: utils_hosts_aws
    when: infra == 'aws'

- name: Fortinet FortiAnalyzer roles
  hosts: fortianalyzer
  connection: httpapi
  gather_facts: no
  vars_files: 
    - main.yml
    - "{{infra}}.yml"
  tasks:
    - name: FortiAnalyzer to Authorize Fortigate add
      fortinet.fortianalyzer.faz_dvm_cmd_add_device:
        dvm_cmd_add_device:
          adom: "root"
          device:
            adm_pass: "admin"
            adm_usr: "adminadmin"
            desc: 'The device is added via FortiAnalyzer Ansible'
            ip: "10.0.0.104"
            name: "FGTAWSXFPH0A7X9D"
            sn: "FGTAWSXFPH0A7X9D" 
            mgmt_mode: faz
            device action: "promote_unreg"
      register: _add_fortigate
      ignore_errors: true

    - name: Debug FortiAnalyzer to Authorize Fortigate add
      debug:
        var: _add_fortigate

    - name: FortiAnalyzer discovery port (fgfm)
      fortinet.fortianalyzer.faz_cli_system_interface:
        cli_system_interface:
          name: port1
          allowaccess:
          - ping
          - ssh
          - https
          - http
          - fgfm
        state: present
      ignore_errors: true

    - name: Config System Settings (Admin -> Admin Settings)
      fortinet.fortianalyzer.faz_cli_system_admin_setting:
        cli_system_admin_setting:
          idle_timeout: 28800
          idle_timeout_api: 28800
          idle_timeout_gui: 28800
          webadmin_language: english
          https_port: 443
          http_port: 80
          gui-theme: red
          access-banner: disable
          admin-https-redirect: disable
          objects-force-deletion: disable
          shell-access: disable
          show-add-multiple: disable
          show-checkbox-in-table: disable
          show-device-import-export: disable
          show-fct-manager: disable
          show-hostname: disable
          show-log-forwarding: disable
      ignore_errors: true

    - name: Create System Settings profile (Admin -> Profile)
      fortinet.fortianalyzer.faz_cli_system_admin_profile:
        cli_system_admin_profile:
          profileid: MyProfile
          description: This is MyProfile created by Ansible
          system-setting: read
          adom-switch: read
          device-manager: read-write
          update-incidents: read-write
          realtime-monitor: read-write
          execute-playbook: read-write
          fabric-viewer: read
          report-viewer: read-write
          run-report: read-write
          triage-events: read-write
        state: present
      ignore_errors: true

    - name: Create System Settings admin (Admin -> Administrators)
      fortinet.fortianalyzer.faz_cli_system_admin_user:
        cli_system_admin_user:
          userid: myadmin
          description: 'My admin user created by Ansible'
          change-password: disable
          email-address: 'myadmin@ansible.com'
          profileid: MyProfile
          two-factor-auth: disable
        state: present
      ignore_errors: true

    - name: Create System Settings Log File Management (Advanced -> File Management)
      fortinet.fortianalyzer.faz_cli_system_autodelete:
        cli_system_autodelete:
          log-auto-deletion:
            retention: days
            runat: 2 #2:00
            value: 200
            status: enable
          report-auto-deletion:
            retention: days
            runat: 3 #3:00
            value: 300
            status: enable
          dlp-files-auto-deletion:
            retention: days
            runat: 4 #4:00
            value: 400
            status: enable
          quarantine-files-auto-deletion:
            retention: days
            runat: 5 #2:00
            value: 500
            status: enable
      ignore_errors: true

- name: "Get FortiAnalyzer facts dvmdb_adom {{ domain }}"
  fortinet.fortianalyzer.faz_fact:
    facts:
        selector: dvmdb_adom
        params:
          adom: "root"
  ignore_errors: yes

- name: Get FortiAnalyzer facts dvmdb_device
  fortinet.fortianalyzer.faz_fact:
    facts:
        selector: dvmdb_device
        params:
            adom: "root"
            device: ""
  ignore_errors: yes