---

- name: Get dynamic Fortinet nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - main.yml
  tasks:
  - debug:
      var: ansible_password
  - include_role: 
      name: utils_hosts_vmware
    when: infra == 'vmware'
  - include_role:
      name: utils_hosts_aws
    when: infra == 'aws'

- name: Fortinet FortiGate roles
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars_files:
    - main.yml
    - "{{infra}}.yml"  
  tasks:
    - include_role: 
        name: fortigate_setup_wmware
      when: infra == 'vmware'
    - include_role: 
        name: fortigate_setup_aws
      when: infra == 'aws'
    - include_role: 
        name: fortigate_access_aws
      when: infra == 'aws'
    - include_role: 
        name: fortigate_config_network
    - include_role: 
        name: fortigate_create_rules
        #name: fortigate_create_rules_day2reorder
    - include_role: 
        name: fortigate_gather_facts
    - include_role: 
        name: fortigate_connect_fortianalyzer
