---

domain: "root"

ansible_network_os: fortinet.fortianalyzer.fortianalyzer
ansible_connection: httpapi
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 443

fortinet_admin_password: "{{ ansible_password | default('adminadmin') }}" 

api_config:
  - "config system admin user"
  - "edit admin"
  - "set rpc-permit read-write"
  - "next"
  - "end"
  - "exit"

