---

- name: Gather facts from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ domain }}"
    selectors:
      - selector: "firewall_policy"
    #  - selector: "system_interface"
    #  - selector: "firewall_address"
  register: _fortinet_facts
  ignore_errors: yes
  
- name: Debug FortiGate Facts
  debug:
    var: _fortinet_facts