---

# https://galaxy.ansible.com/ui/repo/published/fortinet/fortios/content/module/fortios_configuration_fact/
- name: Gather policy facts from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: "firewall_policy"
    #  - selector: "system_interface"
    #  - selector: "firewall_address"
  register: _fortinet_policy_facts

- name: Debug FortiGate Policy Facts
  debug:
    var: _fortinet_policy_facts

- name: Gather system status from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: "system_status"
  register: _fortinet_system_status_facts

- name: Debug FortiGate System Status Facts
  debug:
    var: _fortinet_system_status_facts

- name: Gather system fortiguard from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: "system_fortiguard"
  register: _fortinet_system_fortiguard_facts

- name: Debug FortiGate System Fortiguard Facts
  debug:
    var: _fortinet_system_fortiguard_facts

- name: Gather system admin from Fortinet FortiGate
  fortinet.fortios.fortios_configuration_fact:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: "system_admin"
  register: _fortinet_system_admin_facts

- name: Debug FortiGate System Admin Facts
  debug:
    var: _fortinet_system_admin_facts

- name: Execute a command
  fortinet.fortios.fortios_switch_controller_custom_command:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    state: "present"
    switch_controller_custom_command:
      command: "get system fortiguard-service status"
