---

- name: Debug FortiGate device discovery
  debug:
    var: hostvars[groups['fortigate'][0]].private_ip_address

- name: Discovering FortiGate device from FortiManager 
  fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
    bypass_validation: true
    enable_log: true
    dvm_cmd_discover_device:
      device:
        adm_pass: "{{ adm_pass }}"
        adm_usr: "{{ adm_usr }}"
        ip: "{{ hostvars[groups['fortigate'][0]].private_ip_address }}"
  register: _probed_fortigate

- name: Debug FortiGate device discovery
  debug:
    var: _probed_fortigate

- name: Add FortiGate device to FortiManager
  fortinet.fortimanager.fmgr_dvm_cmd_add_device:
    dvm_cmd_add_device:
      adom: "{{ domain }}"
      device:
        adm_usr: '{{ _probed_fortigate.meta.response_data.device.adm_usr }}'
        adm_pass: '{{ _probed_fortigate.meta.response_data.device.adm_pass }}'
        desc: 'The device was added using Ansible'
        ip: '{{ _probed_fortigate.meta.response_data.device.ip }}'
        mgmt_mode: 'fmg'
        name: '{{ _probed_fortigate.meta.response_data.device.name }}'
        sn: '{{ _probed_fortigate.meta.response_data.device.sn }}'

- name: Creation of a FortiManager Device Group
  fortinet.fortimanager.fmgr_dvmdb_group:
    adom: "{{ domain }}"
    dvmdb_group:
      name: "GroupFortiGate"
      os_type: unknown
      type: normal
    state: present

- name: Add FortiGate as a Group member
  fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
    adom: "{{ domain }}"
    dvmdb_group_objectmember:
      name: "{{ _probed_fortigate.meta.response_data.device.hostname }}"
      vdom: "{{ domain }}"
    group: "GroupFortiGate"
    state: present
  