---

- name: Reoder Rules
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "{{ item.mkey }}"
    #before: "1"
    after: "{{ fg_fw_rules|length - index}}"
  loop: "{{ fg_fw_rules|reverse }}"
  loop_control:
    index_var: index

