---

- name: Reoder Rules (before)
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "{{ item.policyid }}"
    before: "{{ item.before }}"
  when: item.before is defined
  loop: "{{ fg_fw_rules }}"

- name: Reoder Rules (after)
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "{{ item.policyid }}"
    after: "{{ item.after }}"
  when: item.after is defined
  loop: "{{ fg_fw_rules }}"
