---

- name: Gather policy from Fortigate
  fortinet.fortios.fortios_configuration_fact: 
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: firewall_policy
  register: _fg_facts

- name: Reoder Rules
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "{{ item.0.policyid }}"
    before: "{{ fg_fw_rules|length - index}}"
    #after: "{{ fg_fw_rules|length - index}}"
  when: item.0.policyid != item.1.mkey
  # with_nested:
  #   - "{{ _fg_facts.results|reverse }}"
  #   - "{{ fg_fw_rules|reverse }}"
  loop: "{{ _fg_facts.results|product(fg_fw_rules)|list }}"
  loop_control:
    index_var: index

