---

- name: Gather policy from Fortigate
  fortinet.fortios.fortios_configuration_fact: 
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    selectors:
      - selector: firewall_policy
  register: _fg_facts

- name: Reoder Rules
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "{{ item.policyid }}"
    before: "{{ item.before }}"
    #before: "{{ fg_fw_rules|length - index}}"
  #when: (index + 1) != item.0.order
  # with_nested:
  #   - "{{ _fg_facts.results|reverse }}"
  #   - "{{ fg_fw_rules|reverse }}"
  # loop: "{{ _fg_facts.meta[0].results|product(fg_fw_rules)|list }}"
  when: item.before is defined
  loop: "{{ fg_fw_rules }}"
  # loop_control:
  #   index_var: index
