---
# main rule for Fortigate

- name: Start loop for rules
  include_tasks: rule_loop.yml
  loop: "{{ fg_fw_rules }}"
  loop_control:
    label: "{{ _rule.name }}"
    loop_var: _rule
  when: fg_fw_rules | length > 0 


- name: Reoder Rules
  fortios_firewall_policy:
    vdom: "{{ domain }}"
    access_token: "{{ fortigate_token }}"
    action: "move"
    self: "4"
    #after: "1"
    before: "1"
  #when: item.mkey > 
  #loop: "{{ fg_fw_rules }}"
