---

- name: Query VPCs
  amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_vpc_name }}"
  register: vpc

- name: Query Subnets 1
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_subnet_name1 }}"
  register: subnet1

- name: Query Subnets 2
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_subnet_name2 }}"
  register: subnet2

- name: Query Route Tables
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_rt_name }}"
  register: rtb

- name: Terminate FortiGate instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_fgt_instance_name }}"

- name: Terminate FortiAnalyzer instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_faz_instance_name }}"

- name: Terminate FortiManager instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_fmg_instance_name }}"

- name: Delete Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_sg_name }}"
    region: "{{ ec2_vpc_region }}"
    state: absent

- debug:
    var: subnet1

- name: Delete ENI1
  amazon.aws.ec2_eni:
    #private_ip_address: 172.31.0.20
    subnet_id: "{{ subnet1.subnet.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
  register: eni1

- name: Delete ENI2
  amazon.aws.ec2_eni:
    #private_ip_address: 172.31.0.20
    subnet_id: "{{ subnet2.subnet.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
  register: eni2

- name: Delete Subnet in VPC 1
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ subnet1.subnets[0].cidr_block }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0 and subnet1.subnets | length > 0

- name: Delete Subnet in VPC 2
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ subnet2.subnets[0].cidr_block }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0 and subnet2.subnets | length > 0

- name: Delete Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    route_table_id: "{{ rtb.route_tables[0].id }}"
    lookup: id
    state: absent
  when: vpc.vpcs | length > 0 and rtb.route_tables | length > 0

- name: Delete Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
  when: vpc.vpcs | length > 0

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    region: "{{ ec2_vpc_region }}"
    cidr_block: "{{ vpc.vpcs[0].cidr_block }}"
    state: absent
  when: vpc.vpcs | length > 0

