---

domain: "root"

ansible_network_os: fortinet.fortimanager.fortimanager
ansible_connection: httpapi
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 443

fortinet_admin_password: "{{ ansible_password | default('adminadmin') }}" 

api_config:
  - "config system admin user"
  - "edit admin"
  - "set rpc-permit read-write"
  - "next"
  - "end"
  # # Skip pop up in most recent versions
  # - config fmupdate fds-setting
  # - set fortiguard-anycast enable
  # - set fortiguard-anycast-source aws
  # - end
  - "exit"

