---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html
# https://www.mail-archive.com/ansible-project@googlegroups.com/msg39525.html 
- name: Set admin initial password
  ansible.builtin.expect:
    command: "ssh -o StrictHostKeyChecking=no admin@{{ groups['fortigate'][0] }}"
    responses:
      # 'Are you sure you want to continue connecting (yes/no/[fingerprint])': "yes"
      # 'You are forced to change your password. Please input a new password.'
      's password:':
        - "{{ hostvars[groups['fortigate'][0]].instance_id }}"
        - "{{ new_password }}"  # in case setup was already run
      'New Password:': "{{ new_password }}" 
      'Confirm Password:': "{{ new_password }}"
      'FGT': "exit"
  no_log: false # hide passwords on logs
  ignore_errors: true

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection

# - name: Change admin password
#   ansible.builtin.expect:
#     command: "ssh -o StrictHostKeyChecking=no admin@{{ groups['fortigate'][0] }}"
#     responses:
#       '.* password:': "{{ init_password }}" 
#       'FortiGate-VM64 # ': "config system admin"
#       'FortiGate-VM64 \(admin\) #':
#         - "edit admin"
#         - "set password {{ new_password }}"
#         - "end"
#   no_log: false # hide passwords on logs 
      
# - name: Update VM license
#   ansible.builtin.expect:
#     command: "ssh -o StrictHostKeyChecking=no admin@{{ hostvars[groups['fortigate'][0]].ansible_host }}"
#     responses:
#       '.* password': "{{ new_password }}" 
#       'FortiGate-VM64 # ': "execute restore vmlicense ftp {{ lic_filemame }} {{ lic_ftp_server }}"
#       'Do you want to continue\? \(y/n\)': "y"
#   no_log: false # hide passwords on logs 
#   timeout: 60
#   ignore_errors: yes

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  delegate_to: localhost
  